# Generated by Django 5.1.7 on 2025-03-12 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AlbumMainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_photo', to='albums.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albumphoto')),
            ],
        ),
    ]
