# Generated by Django 5.1.7 on 2025-03-11 21:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Полное название госпиталя', max_length=100)),
                ('address', models.CharField(help_text='Подробный адрес до госпиталя', max_length=200)),
                ('url', models.URLField(help_text='Опционально: ссылка на сайт госпиталя, если таковой есть', null=True)),
                ('url_on_map', models.URLField(help_text='Ссылка на местоположение госпиталя в Яндекс Картах, например, https://yandex.ru/maps/-/CHBl44Ny')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPhone',
            fields=[
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Телефон для связи с госпиталем в формате: +79999999999', max_length=128, primary_key=True, region='RU', serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hospitals.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фотография госпиталя с улицы для упрощения поиска', upload_to='photos/%Y/%m/%d')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='hospitals.hospital')),
            ],
        ),
    ]
