# Generated by Django 5.1.7 on 2025-03-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalphone',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalphone',
            name='phone',
            field=models.CharField(help_text='Телефон для связи с госпиталем в формате: +79999999999', max_length=12, primary_key=True, serialize=False),
        ),
    ]
