# Generated by Django 5.1.7 on 2025-03-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospitalphone_comment_alter_hospitalphoto_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalphone',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Комментарий к номеру телефона, например, Справочная', max_length=63),
            preserve_default=False,
        ),
    ]
