# Generated by Django 5.1.7 on 2025-03-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOfBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Полное имя члена правления Фонда, максимум 100 символов', max_length=100)),
                ('post', models.CharField(help_text='Должность члена правления Фонда, например, Председатель', max_length=100)),
                ('biography', models.TextField(help_text='Краткая биография члена правления Фонда')),
                ('image', models.ImageField(upload_to='board')),
            ],
        ),
    ]
