# Generated by Django 5.1.7 on 2025-03-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberofboard',
            name='biography',
            field=models.TextField(blank=True, help_text='Краткая биография члена правления Фонда'),
        ),
        migrations.AlterField(
            model_name='memberofboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board/%Y/%m/%d'),
        ),
    ]
