# Generated by Django 5.1.7 on 2025-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberofboard',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
