# Generated by Django 5.1.7 on 2025-03-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_memberofboard_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberofboard',
            options={'verbose_name': 'member of board', 'verbose_name_plural': 'members of board'},
        ),
        migrations.AlterField(
            model_name='memberofboard',
            name='image',
            field=models.ImageField(upload_to='board/%Y/%m/%d'),
        ),
    ]
